version: '3.5'

services:
  customer_db:
    container_name: customer_db_container
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - 5435:5432
    networks:
      - postgres
    restart: unless-stopped

  fraud_db:
    container_name: fraud_db_container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # The PostgreSQL default database (automatically created at first launch)
      - POSTGRES_DB=fraud
    volumes:
      - postgres:/data/postgres
    ports:
      - 5436:5432
    networks:
      - postgres
    restart: unless-stopped

  #  FIXME! Working incorrectly!
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - fraud_db
      - customer_db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 5052
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5052:5052
    networks:
      - postgres

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: