spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          #          lb - load balancer???
          uri: lb://CUSTOMER
          predicates:
              - Path=/api/v1/customer/**
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: Http://localhost:8761/eureka
    #    Default setting below
    fetch-registry: true
    register-with-eureka: true